 /* This file generated automatically - do not edit */

#include "genblitter.h"

struct blitop blitops[256] = {
 /* 00 */  { "0", 0 },
 /* 01 */  { "~(srcc | srcb | srca)", 7 },
 /* 02 */  { "(srcc & ~(srcb | srca))", 7 },
 /* 03 */  { "~(srcb | srca)", 3 },
 /* 04 */  { "(srcb & ~(srcc | srca))", 7 },
 /* 05 */  { "~(srcc | srca)", 5 },
 /* 06 */  { "(~srca & (srcb ^ srcc))", 7 },
 /* 07 */  { "~(srca | (srcc & srcb))", 7 },
 /* 08 */  { "(srcc & srcb & ~srca)", 7 },
 /* 09 */  { "~(srca | (srcb ^ srcc))", 7 },
 /* 0a */  { "(srcc & ~srca)", 5 },
 /* 0b */  { "~(srca | (~srcc & srcb))", 7 },
 /* 0c */  { "(srcb & ~srca)", 3 },
 /* 0d */  { "~(srca | (~srcb & srcc))", 7 },
 /* 0e */  { "(~srca & (srcb | srcc))", 7 },
 /* 0f */  { "~srca", 1 },
 /* 10 */  { "(srca & ~(srcc | srcb))", 7 },
 /* 11 */  { "~(srcc | srcb)", 6 },
 /* 12 */  { "(~srcb & (srca ^ srcc))", 7 },
 /* 13 */  { "~(srcb | (srcc & srca))", 7 },
 /* 14 */  { "(~srcc & (srca ^ srcb))", 7 },
 /* 15 */  { "~(srcc | (srcb & srca))", 7 },
 /* 16 */  { "((~srca & (srcb ^ srcc)) | ~(srcc | srcb | ~srca))", 7 },
 /* 17 */  { "~((srcb | srca) & (srcc | (srcb & srca)))", 7 },
 /* 18 */  { "((srcc & srcb & ~srca) | ~(srcc | srcb | ~srca))", 7 },
 /* 19 */  { "~((srcc | srcb) & (srca | ~(srcc & srcb)))", 7 },
 /* 1a */  { "((srcc & ~srca) | ~(srcc | srcb | ~srca))", 7 },
 /* 1b */  { "~((srcb | (srcc & srca)) & (~srcc | srca))", 7 },
 /* 1c */  { "((srcb & ~srca) | ~(srcc | srcb | ~srca))", 7 },
 /* 1d */  { "~((srcc | (srcb & srca)) & (~srcb | srca))", 7 },
 /* 1e */  { "(srca ^ (srcb | srcc))", 7 },
 /* 1f */  { "~(srca & (srcc | srcb))", 7 },
 /* 20 */  { "(srcc & ~srcb & srca)", 7 },
 /* 21 */  { "~(srcb | (srca ^ srcc))", 7 },
 /* 22 */  { "(srcc & ~srcb)", 6 },
 /* 23 */  { "~(srcb | (~srcc & srca))", 7 },
 /* 24 */  { "(~(srcc | ~srcb | srca) | (srcc & ~srcb & srca))", 7 },
 /* 25 */  { "~((srcc | srca) & (srcb | ~(srcc & srca)))", 7 },
 /* 26 */  { "((srcc & ~srcb) | ~(srcc | ~srcb | srca))", 7 },
 /* 27 */  { "~((srcb | (~srcc & srca)) & (srcc | srca))", 7 },
 /* 28 */  { "(srcc & (srca ^ srcb))", 7 },
 /* 29 */  { "(~(srcc | srcb | srca) | (srcc & (srca ^ srcb)))", 7 },
 /* 2a */  { "(srcc & ~(srcb & srca))", 7 },
 /* 2b */  { "(~(srcb | srca) | (srcc & ~(srcb & srca)))", 7 },
 /* 2c */  { "((srcb & ~srca) | (srcc & ~(srcb | ~srca)))", 7 },
 /* 2d */  { "(srca ^ (srcb | ~srcc))", 7 },
 /* 2e */  { "((srcc & ~(srcb & srca)) | (srcb & ~srca))", 7 },
 /* 2f */  { "~(srca & (~srcc | srcb))", 7 },
 /* 30 */  { "(~srcb & srca)", 3 },
 /* 31 */  { "~(srcb | (~srca & srcc))", 7 },
 /* 32 */  { "(~srcb & (srca | srcc))", 7 },
 /* 33 */  { "~srcb", 2 },
 /* 34 */  { "(~(srcc | ~srcb | srca) | (~srcb & srca))", 7 },
 /* 35 */  { "~((srcc | srca) & (srcb | ~srca))", 7 },
 /* 36 */  { "(srcb ^ (srca | srcc))", 7 },
 /* 37 */  { "~(srcb & (srcc | srca))", 7 },
 /* 38 */  { "((srcc & srcb & ~srca) | ~(srcb | ~srca))", 7 },
 /* 39 */  { "(srcb ^ (srca | ~srcc))", 7 },
 /* 3a */  { "((srcc & ~srca) | ~(srcb | ~srca))", 7 },
 /* 3b */  { "~(srcb & (~srcc | srca))", 7 },
 /* 3c */  { "(srcb ^ srca)", 3 },
 /* 3d */  { "(~(srcc | srca) | (srcb ^ srca))", 7 },
 /* 3e */  { "((srcc & ~srca) | (srcb ^ srca))", 7 },
 /* 3f */  { "~(srca & srcb)", 3 },
 /* 40 */  { "(~srcc & srcb & srca)", 7 },
 /* 41 */  { "~(srcc | (srca ^ srcb))", 7 },
 /* 42 */  { "(~(~srcc | srcb | srca) | (~srcc & srcb & srca))", 7 },
 /* 43 */  { "~((srcb | srca) & (srcc | ~(srcb & srca)))", 7 },
 /* 44 */  { "(~srcc & srcb)", 6 },
 /* 45 */  { "~(srcc | (~srcb & srca))", 7 },
 /* 46 */  { "(~(~srcc | srcb | srca) | (~srcc & srcb))", 7 },
 /* 47 */  { "~((srcb | srca) & (srcc | (~srcb & srca)))", 7 },
 /* 48 */  { "(srcb & (srca ^ srcc))", 7 },
 /* 49 */  { "(~(srcc | srcb | srca) | (srcb & (srca ^ srcc)))", 7 },
 /* 4a */  { "(~(~srcc | srca) | (~srcc & srcb & srca))", 7 },
 /* 4b */  { "(srca ^ (srcc | ~srcb))", 7 },
 /* 4c */  { "(srcb & ~(srcc & srca))", 7 },
 /* 4d */  { "(~(srcc | srca) | (srcb & ~(srcc & srca)))", 7 },
 /* 4e */  { "((srcc & ~srca) | (srcb & ~(srcc & srca)))", 7 },
 /* 4f */  { "~(srca & (srcc | ~srcb))", 7 },
 /* 50 */  { "(~srcc & srca)", 5 },
 /* 51 */  { "~(srcc | (~srca & srcb))", 7 },
 /* 52 */  { "(~(~srcc | srcb | srca) | (~srcc & srca))", 7 },
 /* 53 */  { "~((srcb | srca) & (srcc | ~srca))", 7 },
 /* 54 */  { "(~srcc & (srca | srcb))", 7 },
 /* 55 */  { "~srcc", 4 },
 /* 56 */  { "(srcc ^ (srcb | srca))", 7 },
 /* 57 */  { "~((srcb | srca) & srcc)", 7 },
 /* 58 */  { "((srcc & srcb & ~srca) | ~(srcc | ~srca))", 7 },
 /* 59 */  { "(srcc ^ (srca | ~srcb))", 7 },
 /* 5a */  { "(srcc ^ srca)", 5 },
 /* 5b */  { "(~(srcb | srca) | (srcc ^ srca))", 7 },
 /* 5c */  { "((srcb & ~srca) | ~(srcc | ~srca))", 7 },
 /* 5d */  { "~(srcc & (~srcb | srca))", 7 },
 /* 5e */  { "((srcb & ~srca) | (srcc ^ srca))", 7 },
 /* 5f */  { "~(srca & srcc)", 5 },
 /* 60 */  { "(srca & (srcb ^ srcc))", 7 },
 /* 61 */  { "(~(srcc | srcb | srca) | (srca & (srcb ^ srcc)))", 7 },
 /* 62 */  { "(~(~srcc | srcb) | (~srcc & srcb & srca))", 7 },
 /* 63 */  { "(srcb ^ (srcc | ~srca))", 7 },
 /* 64 */  { "(~(srcc | ~srcb) | (srcc & ~srcb & srca))", 7 },
 /* 65 */  { "(srcc ^ (srcb | ~srca))", 7 },
 /* 66 */  { "(srcc ^ srcb)", 6 },
 /* 67 */  { "(~(srca | (srcc & srcb)) | (srcc ^ srcb))", 7 },
 /* 68 */  { "((srcc & (srca ^ srcb)) | (~srcc & srcb & srca))", 7 },
 /* 69 */  { "~(srcc ^ srca ^ srcb)", 7 },
 /* 6a */  { "(srcc ^ (srca & srcb))", 7 },
 /* 6b */  { "(~(srcb | srca) | (srcc ^ (srca & srcb)))", 7 },
 /* 6c */  { "(srcb ^ (srca & srcc))", 7 },
 /* 6d */  { "(~(srcc | srca) | (srcb ^ (srca & srcc)))", 7 },
 /* 6e */  { "((~srca & (srcb | srcc)) | (srcc ^ srcb))", 7 },
 /* 6f */  { "(~srca | (srcc ^ srcb))", 7 },
 /* 70 */  { "(srca & ~(srcc & srcb))", 7 },
 /* 71 */  { "(~(srcc | srcb) | (srca & ~(srcc & srcb)))", 7 },
 /* 72 */  { "((srcc & ~srcb) | (srca & ~(srcc & srcb)))", 7 },
 /* 73 */  { "~(srcb & (srcc | ~srca))", 7 },
 /* 74 */  { "(~(srcc | ~srcb) | (~srcb & srca))", 7 },
 /* 75 */  { "~(srcc & (srcb | ~srca))", 7 },
 /* 76 */  { "((~srcb & srca) | (srcc ^ srcb))", 7 },
 /* 77 */  { "~(srcb & srcc)", 6 },
 /* 78 */  { "(srca ^ (srcb & srcc))", 7 },
 /* 79 */  { "(~(srcc | srcb) | (srca ^ (srcb & srcc)))", 7 },
 /* 7a */  { "((~srcb & srca) | (srcc ^ srca))", 7 },
 /* 7b */  { "(~srcb | (srcc ^ srca))", 7 },
 /* 7c */  { "((~srcc & srca) | (srcb ^ srca))", 7 },
 /* 7d */  { "(~srcc | (srcb ^ srca))", 7 },
 /* 7e */  { "((~srca & (srcb | srcc)) | ~(~srca | (srcc & srcb)))", 7 },
 /* 7f */  { "~(srca & srcb & srcc)", 7 },
 /* 80 */  { "(srcc & srcb & srca)", 7 },
 /* 81 */  { "(~(srcc | srcb | srca) | (srcc & srcb & srca))", 7 },
 /* 82 */  { "(srcc & ~(srca ^ srcb))", 7 },
 /* 83 */  { "(~(srcb | srca) | (srcc & srcb & srca))", 7 },
 /* 84 */  { "(srcb & ~(srca ^ srcc))", 7 },
 /* 85 */  { "(~(srcc | srca) | (srcc & srcb & srca))", 7 },
 /* 86 */  { "((~srca & (srcb ^ srcc)) | (srcc & srcb & srca))", 7 },
 /* 87 */  { "~(srca ^ (srcb & srcc))", 7 },
 /* 88 */  { "(srcc & srcb)", 6 },
 /* 89 */  { "(~(srcc | srcb | srca) | (srcc & srcb))", 7 },
 /* 8a */  { "(srcc & (srcb | ~srca))", 7 },
 /* 8b */  { "(~(srca | (~srcc & srcb)) | (srcc & srcb))", 7 },
 /* 8c */  { "(srcb & (srcc | ~srca))", 7 },
 /* 8d */  { "(~(srca | (~srcb & srcc)) | (srcc & srcb))", 7 },
 /* 8e */  { "((srcc & ~srca) | (srcb & (srcc | ~srca)))", 7 },
 /* 8f */  { "(~srca | (srcc & srcb))", 7 },
 /* 90 */  { "(srca & ~(srcb ^ srcc))", 7 },
 /* 91 */  { "(~(srcc | srcb) | (srcc & srcb & srca))", 7 },
 /* 92 */  { "((~srcb & (srca ^ srcc)) | (srcc & srcb & srca))", 7 },
 /* 93 */  { "~(srcb ^ (srca & srcc))", 7 },
 /* 94 */  { "((~srcc & (srca ^ srcb)) | (srcc & srcb & srca))", 7 },
 /* 95 */  { "~(srcc ^ (srca & srcb))", 7 },
 /* 96 */  { "(srcc ^ srca ^ srcb)", 7 },
 /* 97 */  { "~((srcb | srca) & (srcc ^ (srca & srcb)))", 7 },
 /* 98 */  { "((srcc & srcb) | (srca & ~(srcc | srcb)))", 7 },
 /* 99 */  { "~(srcc ^ srcb)", 6 },
 /* 9a */  { "(srcc ^ (srca & ~srcb))", 7 },
 /* 9b */  { "~((srca | (~srcc & srcb)) & (srcc ^ srcb))", 7 },
 /* 9c */  { "(srcb ^ (srca & ~srcc))", 7 },
 /* 9d */  { "~((srca | (~srcb & srcc)) & (srcc ^ srcb))", 7 },
 /* 9e */  { "((srcc & srcb) | (srca ^ (srcb | srcc)))", 7 },
 /* 9f */  { "~(srca & (srcc ^ srcb))", 7 },
 /* a0 */  { "(srcc & srca)", 5 },
 /* a1 */  { "(~(srcc | srcb | srca) | (srcc & srca))", 7 },
 /* a2 */  { "(srcc & (srca | ~srcb))", 7 },
 /* a3 */  { "(~(srcb | srca) | (srcc & srca))", 7 },
 /* a4 */  { "((srcb & ~(srcc | srca)) | (srcc & srca))", 7 },
 /* a5 */  { "~(srcc ^ srca)", 5 },
 /* a6 */  { "(srcc ^ (srcb & ~srca))", 7 },
 /* a7 */  { "~((srcb | srca) & (srcc ^ srca))", 7 },
 /* a8 */  { "(srcc & (srca | srcb))", 7 },
 /* a9 */  { "~(srcc ^ (srcb | srca))", 7 },
 /* aa */  { "srcc", 4 },
 /* ab */  { "(~(srcb | srca) | srcc)", 7 },
 /* ac */  { "((srcb & ~srca) | (srcc & srca))", 7 },
 /* ad */  { "((srcb & ~srca) | (srcc ^ ~srca))", 7 },
 /* ae */  { "(srcc | (srcb & ~srca))", 7 },
 /* af */  { "(~srca | srcc)", 5 },
 /* b0 */  { "(srca & (srcc | ~srcb))", 7 },
 /* b1 */  { "(~(srcb | (~srca & srcc)) | (srcc & srca))", 7 },
 /* b2 */  { "((srcc & ~srcb) | (srca & (srcc | ~srcb)))", 7 },
 /* b3 */  { "(~srcb | (srcc & srca))", 7 },
 /* b4 */  { "(srca ^ (srcb & ~srcc))", 7 },
 /* b5 */  { "~((srcb | ~srca) & (srcc ^ srca))", 7 },
 /* b6 */  { "((srcc & srca) | (srcb ^ (srca | srcc)))", 7 },
 /* b7 */  { "~(srcb & (srcc ^ srca))", 7 },
 /* b8 */  { "((srcc & srcb) | (~srcb & srca))", 7 },
 /* b9 */  { "((~srcb & srca) | (srcc ^ ~srcb))", 7 },
 /* ba */  { "(srcc | (~srcb & srca))", 7 },
 /* bb */  { "(~srcb | srcc)", 6 },
 /* bc */  { "((srcc & srca) | (srcb ^ srca))", 7 },
 /* bd */  { "(~(srcc | srca) | (srcc & srca) | (srcb ^ srca))", 7 },
 /* be */  { "(srcc | (srcb ^ srca))", 7 },
 /* bf */  { "(srcc | ~(srca & srcb))", 7 },
 /* c0 */  { "(srcb & srca)", 3 },
 /* c1 */  { "(~(srcc | srcb | srca) | (srcb & srca))", 7 },
 /* c2 */  { "((srcc & ~(srcb | srca)) | (srcb & srca))", 7 },
 /* c3 */  { "~(srcb ^ srca)", 3 },
 /* c4 */  { "(srcb & (srca | ~srcc))", 7 },
 /* c5 */  { "(~(srcc | srca) | (srcb & srca))", 7 },
 /* c6 */  { "(srcb ^ (~srca & srcc))", 7 },
 /* c7 */  { "~((srcc | srca) & (srcb ^ srca))", 7 },
 /* c8 */  { "(srcb & (srca | srcc))", 7 },
 /* c9 */  { "~(srcb ^ (srcc | srca))", 7 },
 /* ca */  { "((srcc & ~srca) | (srcb & srca))", 7 },
 /* cb */  { "((srcc & ~srca) | (srcb ^ ~srca))", 7 },
 /* cc */  { "srcb", 2 },
 /* cd */  { "(~(srcc | srca) | srcb)", 7 },
 /* ce */  { "((srcc & ~srca) | srcb)", 7 },
 /* cf */  { "(~srca | srcb)", 3 },
 /* d0 */  { "(srca & (srcb | ~srcc))", 7 },
 /* d1 */  { "(~(srcc | srcb) | (srcb & srca))", 7 },
 /* d2 */  { "(srca ^ (~srcb & srcc))", 7 },
 /* d3 */  { "~((srcc | ~srca) & (srcb ^ srca))", 7 },
 /* d4 */  { "((~srcc & srcb) | (srca & (srcb | ~srcc)))", 7 },
 /* d5 */  { "(~srcc | (srcb & srca))", 7 },
 /* d6 */  { "((srcb & srca) | (srcc ^ (srcb | srca)))", 7 },
 /* d7 */  { "~(srcc & (srcb ^ srca))", 7 },
 /* d8 */  { "((srcc & srcb) | (~srcc & srca))", 7 },
 /* d9 */  { "((srcb & srca) | ~(srcc ^ srcb))", 7 },
 /* da */  { "((srcb & srca) | (srcc ^ srca))", 7 },
 /* db */  { "(~(srcb | srca) | (srcb & srca) | (srcc ^ srca))", 7 },
 /* dc */  { "(srcb | (~srcc & srca))", 7 },
 /* dd */  { "(~srcc | srcb)", 6 },
 /* de */  { "(srcb | (srcc ^ srca))", 7 },
 /* df */  { "(srcb | ~(srca & srcc))", 7 },
 /* e0 */  { "(srca & (srcb | srcc))", 7 },
 /* e1 */  { "~(srca ^ (srcc | srcb))", 7 },
 /* e2 */  { "((srcc & ~srcb) | (srcb & srca))", 7 },
 /* e3 */  { "((srcc & srca) | ~(srcb ^ srca))", 7 },
 /* e4 */  { "((~srcc & srcb) | (srcc & srca))", 7 },
 /* e5 */  { "((srcb & srca) | ~(srcc ^ srca))", 7 },
 /* e6 */  { "((srcb & srca) | (srcc ^ srcb))", 7 },
 /* e7 */  { "(~(srca | (srcc & srcb)) | (srca & (srcb | srcc)))", 7 },
 /* e8 */  { "((srcc & srcb) | (srca & (srcb | srcc)))", 7 },
 /* e9 */  { "((srcc & srcb) | ~(srca ^ (srcc | srcb)))", 7 },
 /* ea */  { "(srcc | (srcb & srca))", 7 },
 /* eb */  { "(srcc | ~(srcb ^ srca))", 7 },
 /* ec */  { "(srcb | (srcc & srca))", 7 },
 /* ed */  { "(srcb | ~(srcc ^ srca))", 7 },
 /* ee */  { "(srcc | srcb)", 6 },
 /* ef */  { "(~srca | srcc | srcb)", 7 },
 /* f0 */  { "srca", 1 },
 /* f1 */  { "(~(srcc | srcb) | srca)", 7 },
 /* f2 */  { "((srcc & ~srcb) | srca)", 7 },
 /* f3 */  { "(~srcb | srca)", 3 },
 /* f4 */  { "((~srcc & srcb) | srca)", 7 },
 /* f5 */  { "(~srcc | srca)", 5 },
 /* f6 */  { "(srca | (srcc ^ srcb))", 7 },
 /* f7 */  { "(srca | ~(srcb & srcc))", 7 },
 /* f8 */  { "((srcc & srcb) | srca)", 7 },
 /* f9 */  { "(srca | ~(srcc ^ srcb))", 7 },
 /* fa */  { "(srcc | srca)", 5 },
 /* fb */  { "(~srcb | srcc | srca)", 7 },
 /* fc */  { "(srcb | srca)", 3 },
 /* fd */  { "(~srcc | srcb | srca)", 7 },
 /* fe */  { "(srcc | srcb | srca)", 7 },
 /* ff */  { "0xFFFFFFFF", 0 }
};
